Add HJT module
LordRalex/absol pull request #3
Opened 2020-03-26 20:10 UTC by urielsalis

2020-03-27 18:27 UTC, LordRalex requested changes

2020-03-27 18:27 UTC, LordRalex commented on modules/hjt/hjt.go
> +		_, err = ds.ChannelMessageSend(mc.ID, "Invalid URL")
This is the wrong ID. It is ChannelID

2020-03-27 18:27 UTC, LordRalex commented on modules/hjt/hjt.go
> +		_, err = ds.ChannelMessageSend(mc.ID, "Failed to connect to database")
This is the wrong ID. It is ChannelID

2020-03-27 18:27 UTC, LordRalex commented on modules/hjt/hjt.go
> +		logger.Debug().Printf("Invalid url: %s\n%s", pasteLink, err)
We don't need this logging anymore

2020-03-27 18:27 UTC, LordRalex commented on modules/hjt/hjt.go
> +		_, err = ds.ChannelMessageSend(mc.ID, "No matches found")
This is the wrong ID. It is ChannelID

2020-03-27 18:27 UTC, LordRalex commented on modules/hjt/hjt.go
> +		logger.Err().Printf("Failed to pull data from database\n%s", err)
Should tell user as well

2020-03-27 18:27 UTC, LordRalex commented on modules/hjt/hjt.go
> +		_, err = ds.ChannelMessageSend(mc.ID, strings.Join(values, ", "))
This is the wrong ID. It is ChannelID

2020-03-28 00:51 UTC, LordRalex commented
You also need to add this to https://github.com/LordRalex/absol/blob/master/core/module.go#L17
otherwise, we will not load this.

2020-03-28 11:54 UTC, urielsalis commented
Done

2020-03-28 19:56 UTC, merged